### ISSUE TITLE
Data Cleaning & Preparation Before Analysis

### ISSUE THREAD

**Issue by yiting0112** [course-dprep/Airbnb-new-years-eve#18]
Have confirmed variables and dates we're going to use. So have to: 
1. Filter date (26.12.2022~05.01.2023) from calendar.csv.
2. Combine 2 data set.
3. The code runs in a linear fashion adheres to the DRY principles.

**Deliverable:**
Combine 2 data set for the following analysis.
Data adheres to the DRY principles.

**Comment by HNTurer** [comment]
Updated all necessary loops and could output the file.
