### ISSUE TITLE
Brainstorming on Topic

### ISSUE THREAD

**Issue by fleurlemire** [course-dprep/Airbnb-new-years-eve#2]
**Goal:** Our goal is to brainstorm and decide on a topic for our research question regarding Airbnb

At this moment, we are brainstorming about which topic to choose for our research question. We are thinking in the direction of an event. This can be a festival, carnival in Rio de Janeiro, or a concert or something like fashion week. We prefer an event that lasts several days, so we have more data on this event.

Our choice depends on the data which is available, but we are not able to open it right now. If we can open the data and explore this, we can decide which topic to choose. 

**Deliverable:** Deliver a research question about our topic.

**Comment by hannesdatta** [comment]
@fleurlemire -- pls define a clear deliverable and mark in __bold__.

**Comment by fleurlemire** [comment]
The research question is defined and the topic has been chosen. 

**Research Question:** What is the effect of New Year’s eve on Airbnb listings in Capital cities in Europe?
- Capital cities used in the research: London, Paris, Amsterdam, Rome

**Comment by fleurlemire** [comment]
**Summary:** 

The research question is defined and the topic has been chosen.

Research Question: What is the effect of New Year’s eve on Airbnb listings in Capital cities in Europe?

Capital cities used in the research: London, Paris, Amsterdam, Rome

Furthermore, we focus on the following subquestions have been defined: 

- What is the influence of New Year’s eve on the availability of Airbnb listings in Capital cities in Europe?
- What is the influence of New Year’s eve on prices of Airbnb listings in Capital cities in Europe?
- Can check the price/availability effect separately within 4 cities. Or also add one more research question like, “Which city’s Airbnb price/availability is affected by new years eve the most?”

**Comment by Mariellavanerve** [comment]
Summary:
Together in the meeting we brainstormed on the topic and decided to choose New Year's eve for four different capital cities.
