### ISSUE TITLE
Make a start with a code snipper for method: linear regression snippet

### ISSUE THREAD

**Issue by fleurlemire** [course-dprep/Airbnb-new-years-eve#25]
**Goal**: Making a start with a code snipper for our analysis

**Deliverable:** A code snipper which can be used for the linear regression analysis

**Comment by fleurlemire** [comment]
snipper = snippet

**Comment by HNTurer** [comment]
created the loops updated the code snippet

**Comment by fleurlemire** [comment]
**Summary:** Code snippet is added to src/analysis/analyze.R. Some questions need to be answered, therefore, new issues are made.
