### ISSUE TITLE
Try to make a new loop in the R markdown file

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#28]
Deliverable: A loop for all the cities where we gather the prices and store them in a seperate data(sub)set.

**Comment by Mariellavanerve** [comment]
We had a meeting with Hannes and he explained how to debug the loop. Nishtha is going to add this in the R markdown file and check if everything works.

**Comment by NJCStacie** [comment]
_Summary_
We now have created a loop that retrieves the price per city without the dollar sign
