### ISSUE TITLE
write R code snippet to open a dataset from inside airbnb

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/Airbnb-new-years-eve#3]
__Deliverable:__

- code that opens http://data.insideairbnb.com/united-states/ny/new-york-city/2022-12-04/data/listings.csv.gz and loads it into R
- script needs to be tested to run both on mac and windows

**Comment by fleurlemire** [comment]
**Result:**

The following code opens and loads the data into R
It both works and runs for windows and mac

Code snippet:
setwd("--")
reviews <- read.csv("reviews.csv.gz")
View(reviews)
dates <- read.csv("calendar.csv.gz")
View(dates)
listings <- read.csv("listings.csv.gz")
View(listings)
geo <- read.csv("neighbourhoods.geojson")
View(geo)

**Comment by Mariellavanerve** [comment]
Summary:
We wrote together in the meeting a R code snippet that works for all of us. See the snippet above.
