### ISSUE TITLE
please debug

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/Airbnb-new-years-eve#31]
This line used to work, but now it does not. Do you see the error?

https://github.com/course-dprep/Airbnb-new-years-eve/blob/dd692a60ed0545f753101a2be0f6ccf34d09b538/src/data-preparation/Data_exploration.R#L13

**Comment by NJCStacie** [comment]
_Summary_
The code has been debugged and now removes the dollar signs of the price column for the listings data files
