### ISSUE TITLE
Update repository structure after discussing what is not necessary 

### ISSUE THREAD

**Issue by fleurlemire** [course-dprep/Airbnb-new-years-eve#36]
**Goal**: Have a smaller repository which is more clear to the reader

**Deliverable:** Updated repository structure

**Comment by Mariellavanerve** [comment]
We have to look at this: A proper directory structure is integrated (e.g., code in src folder, plots in output folder)

See this link for info: http://pulse.tilburg-digital.com/comments?module_id=6&task_id=task_dprep_6_3_1

**Comment by fleurlemire** [comment]
**Summary:** is updated, also after changing name files
