### ISSUE TITLE
explore types of data

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/Airbnb-new-years-eve#4]
**Dimensions to understand:**
- historical vs. current data (which years, all dates or per month)
- type of information you see per .csv/.csv.gz file (neighborhoods, listings, calendar, ...)

**Comment by NJCStacie** [comment]
We looked at the different types of data on Airbnb provided by insideairbnb.com.
Our main focus was on the calendar date data, since we used this to determine our project topic.

**Comment by Mariellavanerve** [comment]
Summary:
Together we explored the datasets in the meeting. See also the summary of Nishtha.
