### ISSUE TITLE
Make an output file

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#42]
Deliverable; Make an output file based on the analysis and Rmarkdown

**Comment by Mariellavanerve** [comment]
Other teams sometimes hide this pdf. 
-Valentines Day has a pdf file in the scr/analysis with an introduction, variable descriptives with 3 plots, checking assumptions.
- Formula 1 /gen/paper/output with the hypothesis, type of analysis, checking the assumptions with two plots, difference in differences with and without confounds, conclusion and a table.

**Comment by Mariellavanerve** [comment]
I looked at some more teams:
- Effect-of-canal-parade-on-prices: /src/paper/output/ and had 2 pdf's with both one plot.
- What-influences-AirBnB-prices: /src/paper/ made a pdf out of a rmd file with an introduction, data visualization, main analysis, interpretation, implications with a few graphs.
- Start_of_Academic_Year_relationship_with_AirBnB_Market: /final_report.pdf with introduction, methodology, results, conclusion, discussion, references with 6 tables and a figure.

**Comment by Mariellavanerve** [comment]
Look at the valentines day for the logistic regression.

**Comment by fleurlemire** [comment]
**Summary:** Output file has been created under name report.rmd
