### ISSUE TITLE
Preparing the data

### ISSUE THREAD

**Issue by fleurlemire** [course-dprep/Airbnb-new-years-eve#5]
**Goal:** Prepare the data in R, involving dplyr, tidyverse, or data.table. 

Basic programming concepts make use of appropriately to increase speed and minimize errors (e.g., looping, vectorization, writing functions, handling errors/debugging). Additional variables need to be created from the raw data.

**Deliverable:** Dataset which has been prepared and cleaned. The data is ready for analysis.

**Comment by yiting0112** [comment]
Update "Files download" steps in 'src/data-preparation/download_data.R'.
