### ISSUE TITLE
Make a gitignore file

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#50]
Deliverable: A gitignore file is included, ensuring that Git does not track unnecessary files

See link for more info: http://pulse.tilburg-digital.com/comments?module_id=6&task_id=task_dprep_6_3_3

Please look at how other groups did this

**Comment by HNTurer** [comment]
Rproj.user is added to the gitignore file. Rproj.user is a hidden directory where project-specific temporary files (e.g. auto-saved source documents, window-state, etc.) are stored. If you delete it, you will not access to your history or these temporary files. Your project will still work - Rstudio will recreate the directory when you open the project.

**Comment by HNTurer** [comment]
.DS_Store is added to the gitignore file.  DS_Store is a file that stores custom attributes of its containing folder, such as folder view options, icon positions, and other visual information.
