### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#51]
Deliverables:
- The research method is not described in the file yet. 
- We could write a bit about the relevance of our report. 
- The variables used in this study is a picture now but I think it is better to make a table of it (see project link below for how nice this looks).
- Moreover, the running instructions need to be updated. 
- The dependencies should be updated and maybe take a look at this project https://github.com/course-dprep/airbnb-price-calculator because their overview is really nice. It looks like two boxes. 

Their README file is really pretty and the professor wants our file to shine !

**Comment by fleurlemire** [comment]
I added a table with the variables instead of a picture! So bulletpoint three has been done.

**Comment by fleurlemire** [comment]
All, I also updated method, if you still miss anything, let me know, then i will update it again!

**Comment by Mariellavanerve** [comment]
What is left to do: Write about the relevance of our project. Update the running instructions.

**Comment by Mariellavanerve** [comment]
I added the relevance part and the source of airbnb that we used for our project.

**Comment by fleurlemire** [comment]
**Summary:** Method is also updated with reasoning and why we use the methods for which variable
