### ISSUE TITLE
Make a start with explaining the research method

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#6]
**Goal**: Look into the options for the research method. Also look at how other teams did this.

**Deliverable**: Have the options ready with additional information such that we can decide on what method to use.

**Comment by fleurlemire** [comment]
**Summary:**  

Variables have been chosen for the research and based on that, options for the research method have been explored. This is all noted under 'Method' in the readme. Possible research methods are: logistic regression, linear regression and t-test. Moreover, it has been decided which datasets to use for these variables.

**Comment by fleurlemire** [comment]
Summary:

Variables have been chosen for the research and based on that, options for the research method have been explored. This is all noted under 'Method' in the readme. Possible research methods are: logistic regression, linear regression and t-test. Moreover, it has been decided which datasets to use for these variables.

**Comment by fleurlemire** [comment]
**Summary:**

Variables have been chosen for the research and based on that, options for the research method have been explored. This is all noted under 'Method' in the readme. Possible research methods are: logistic regression, linear regression and t-test. Moreover, it has been decided which datasets to use for these variables.
