### ISSUE TITLE
output in clean_data: why do you append complete_data and the four cities? is this correct?

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#75]

**Comment by fleurlemire** [comment]
**Summary:** check on thursday. Only names of files append to complete data, not the data itself

**Comment by fleurlemire** [comment]
@hannesdatta can you maybe explain what you mean? The data itself is not appending. Only the names of the files for the different cities are called: complete_data_'cityname' . It refers too the complete data within the timeframe of that specific city.
