### ISSUE TITLE
rename `New_Years.Rmd` - maybe `audit.Rmd`? Also ensure the doc looks good (right now, the title is `NewYears`, is this intended or does it need to be cleaned still?

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#78]

**Comment by fleurlemire** [comment]
@Mariellavanerve do we keep the pdf markdown also in dataprep folder? then i will update repository structure in readme! otherwise i will change where it is put or do nothing!

**Comment by Mariellavanerve** [comment]
Summary: The file name we changed and also the title of the Rmd.
