### ISSUE TITLE
The generated plots (boxplots) is very slow in Report.pdf. Is it necessary to generate it using all of the data? If not, taking a random sample will speed things up considerably. Also, the labeling is not correct yet. Add a legend.

### ISSUE THREAD

**Issue by Mariellavanerve** [course-dprep/Airbnb-new-years-eve#83]

**Comment by yiting0112** [comment]
For the plots, we input the pdf.file that output from analysis.R.
Also, deleted the code to input dataset of each city. (not necessary in this markdown).

**Comment by Mariellavanerve** [comment]
I checked and it is still lagging a lot. For me it even seems like it did not improve speed...

**Comment by NJCStacie** [comment]
_Summary_
A sample of 10% of the data was used to generate the boxplots. This makes the boxplots load faster, and results in them loading faster.
