### ISSUE TITLE
Create rendered Markdown files

### ISSUE THREAD

**Issue by fleurlemire** [course-dprep/Airbnb-new-years-eve#9]
**Goal:** Allow potential users of our repository to understand the content of such files, and the definition of variables.

**Deliverable:** Meaningful RMarkdown reports which allows potential users to understand the content

Start from motivation of this topic.

**Comment by NJCStacie** [comment]
_Summary_
A draft version of the RMarkdown has been created that includes data summaries, percentages, tables, piecharts, and ggplots.
